#!/bin/bash



# better element ?
./node_modules/.bin/cheerio '.sort-bar h3' |\
# lame, FIXME, Showing 57,989 available code results
sed "s;.* \(Showing\|found\) \([^ ]\+\) .*;\2; ; s;,;;" | grep "." 


