#!/bin/bash
_url_encode(){
	local str="$1"
	node -e "console.log(encodeURIComponent('$str'));"
};
url='https://github.com/search?q='$(_url_encode "$1") # TODO: check whitespace encoding %20 vs + 
echo "# Query: $1" 1>&2
echo "# curl '$url'" 1>&2


count=$(curl -s "$url" | extract-count)
pages=$(( $count / 10 )) # can we change page size ?
pages_cap="${2:-0}"
max_requests=$(($pages<$pages_cap?$pages:$pages_cap))

echo "
# Count: $count
# Pages: $pages, 
# Max Requests(cap): $max_requests
" 1>&2

# REVIEW: startinf from 1 ? or 0 ?
for (( i=1; i <= $max_requests; ++i ))
do
	#sleep 2
	echo "# curl '$url&p=$i'" 1>&2
	curl -s "$url&p=$i"
done


